curl -X POST "http://databaseconnectionexample.azurewebsites.net/class" -H "Content-Type: application/json" -d '

{
    "dept_code": "CISC",
    "class_num": "380",
    "class_name": "Algorithms"
}'
###
curl "http://databaseconnectionexample.azurewebsites.net/class" 