curl -X POST "http://databaseconnectionexample.azurewebsites.net/class" -H "Content-Type: application/json" -d '

{
    "dept_code": "CISC",
    "class_num": "380",
    "class_name": "Algorithms"
}'
###
curl "http://databaseconnectionexample.azurewebsites.net/class" 

###
curl "http://databaseconnectionexample.azurewebsites.net/faculty"

###
curl -X POST "http://databaseconnectionexample.azurewebsites.net/faculty" -H "Content-Type: application/json" -d '
{
    "faculty_id": 1,
    "faculty_first": "first",
    "faculty_last": "last",
    "title_id": 1,
    "prev_load": 2.5,
    "curr_load": 6.0
}'

###
curl -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImVtYWlsIjoid2VidXNlckBzdHRob21hcy5lZHUiLCJwYXNzIjoiJDJiJDEwJEhnQk55RnVTa1lTeDAyS2RkNlNjbU9DWHRzL1o0WFhyQTNDWGJJNWgxUW9ZTC41by5YbVMuIiwiZmFjdWx0eV9pZCI6bnVsbCwiYWNjZXNzX2xldmVsIjoyLCJ0bXAiOm51bGx9LCJpYXQiOjE2NTIzNzIwODAsImV4cCI6MTY1MjQ1ODQ4MH0.r8N-rWWut9J-oJYS477gPFx-QvBTJ_ek5Diad9_4RGg" "https://classy-api.ddns.net/v2/section" 

###
curl "https://classy-api.ddns.net/v2/signup" -X POST -d "email=[web@stthomas.edu]&password=[webdev]"

###
curl "https://classy-api.ddns.net/v2/login" -X POST -d "email=classy-schedule-dev@stthomas.edu&password=classyschedule"

###
curl -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImVtYWlsIjoiY2xhc3N5LXNjaGVkdWxlLWRldkBzdHRob21hcy5lZHUiLCJwYXNzIjoiJDJiJDEwJGtJcUc3b09oczNRbDB4TTNhZ3pIbS5LMTk4ZGRCQW9xT3h5by4yakJRVVR4THNSVjZCbko2IiwiZmFjdWx0eV9pZCI6bnVsbCwiYWNjZXNzX2xldmVsIjozLCJ0bXAiOm51bGx9LCJpYXQiOjE2NTE4NjU0MjIsImV4cCI6MTY1MTk1MTgyMn0.LY5EbarANRCdDxM9j6Ow69msRXDg1tdOnNRB5RlKuvE" "https://classy-api.ddns.net/v2/login/[web@stthomas.edu]" -X PUT -d "access_level=2"

###
curl "https://classy-api.ddns.net/v2/login" -X POST -d "email=webuser@stthomas.edu&password=webpassword"